In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from math import radians, sin, cos, sqrt, atan2

In [4]:
# read csv files
apr_21_df = pd.read_csv('citi_bike_data/website_data_files/202104-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
may_21_df = pd.read_csv('citi_bike_data/website_data_files/202105-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jun_21_df = pd.read_csv('citi_bike_data/website_data_files/202106-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jul_21_df = pd.read_csv('citi_bike_data/website_data_files/202107-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
aug_21_df = pd.read_csv('citi_bike_data/website_data_files/202108-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
sep_21_df = pd.read_csv('citi_bike_data/website_data_files/202109-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
oct_21_df = pd.read_csv('citi_bike_data/website_data_files/202110-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
nov_21_df = pd.read_csv('citi_bike_data/website_data_files/202111-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
dec_21_df = pd.read_csv('citi_bike_data/website_data_files/202112-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jan_22_df = pd.read_csv('citi_bike_data/website_data_files/202201-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
feb_22_df = pd.read_csv('citi_bike_data/website_data_files/202202-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
mar_22_df = pd.read_csv('citi_bike_data/website_data_files/202203-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
apr_22_df = pd.read_csv('citi_bike_data/website_data_files/202204-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
may_22_df = pd.read_csv('citi_bike_data/website_data_files/202205-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jun_22_df = pd.read_csv('citi_bike_data/website_data_files/202206-citbike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jul_22_df = pd.read_csv('citi_bike_data/website_data_files/202207-citbike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
aug_22_df = pd.read_csv('citi_bike_data/website_data_files/202208-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
sep_22_df = pd.read_csv('citi_bike_data/website_data_files/202209-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
oct_22_df = pd.read_csv('citi_bike_data/website_data_files/202210-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
nov_22_df = pd.read_csv('citi_bike_data/website_data_files/202211-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
dec_22_df = pd.read_csv('citi_bike_data/website_data_files/202212-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
jan_23_df = pd.read_csv('citi_bike_data/website_data_files/202301-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
feb_23_df = pd.read_csv('citi_bike_data/website_data_files/202302-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)
mar_23_df = pd.read_csv('citi_bike_data/website_data_files/202303-citibike-tripdata.csv',skiprows=lambda x: x % 5 != 0)

# concatenate the dataframes
sampled_df = pd.concat([apr_21_df, may_21_df, jun_21_df, 
                        jul_21_df, aug_21_df, sep_21_df, 
                        oct_21_df, nov_21_df, dec_21_df, 
                        jan_22_df, feb_22_df, mar_22_df, 
                        apr_22_df, may_22_df, jun_22_df, 
                        jul_22_df, aug_22_df, sep_22_df, 
                        oct_22_df, nov_22_df, dec_22_df, 
                        jan_23_df, feb_23_df, mar_23_df])

# reset the index
sampled_df = sampled_df.reset_index(drop=True)

sampled_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BE78810D746EE516,docked_bike,2021-04-30 00:34:54,2021-04-30 01:03:29,3 Ave & E 112 St,7543.15,E 115 St & Lexington Ave,7599.09,40.795508,-73.941606,40.797911,-73.942300,casual
1,82821A8274B28C53,docked_bike,2021-04-22 05:18:58,2021-04-22 05:23:18,3 Ave & E 112 St,7543.15,Lenox Ave & W 115 St,7627.10,40.795508,-73.941606,40.801194,-73.950074,member
2,DB19F7991DA28B14,docked_bike,2021-04-23 17:38:00,2021-04-23 17:42:35,DeKalb Ave & Hudson Ave,4513.06,Johnson St & Gold St,4668.08,40.689888,-73.981013,40.694749,-73.983625,member
3,AC2320F2CDD43A33,docked_bike,2021-04-22 18:59:33,2021-04-22 19:21:54,E 47 St & Park Ave,6584.12,W 70 St & Amsterdam Ave,7207.08,40.755102,-73.974986,40.777480,-73.982886,member
4,6C6B9EC7F21A5FFA,docked_bike,2021-04-26 06:43:20,2021-04-26 06:47:38,E 47 St & Park Ave,6584.12,E 58 St & 3 Ave,6762.02,40.755102,-73.974986,40.760958,-73.967245,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175287,2FA58696871472C1,classic_bike,2023-03-12 15:27:30,2023-03-12 15:31:39,Vernon Blvd & 50 Ave,6170.02,45 Ave & 21 St,6319.07,40.742327,-73.954117,40.747371,-73.947773,member
12175288,E1F15A1DE1C16A59,classic_bike,2023-03-11 15:01:13,2023-03-11 15:08:05,Vernon Blvd & 50 Ave,6170.02,45 Ave & 21 St,6319.07,40.742327,-73.954117,40.747371,-73.947773,member
12175289,D87208A2A12F9C09,classic_bike,2023-03-16 10:10:16,2023-03-16 10:14:07,11 Ave & W 27 St,6425.04,W 37 St & 10 Ave,6611.02,40.751072,-74.005374,40.756604,-73.997901,member
12175290,6BF0A59B0128F4F1,classic_bike,2023-03-24 18:48:02,2023-03-24 18:55:55,Vernon Blvd & 50 Ave,6170.02,Ash St & Manhattan Ave,6019.04,40.742327,-73.954117,40.740000,-73.950000,member
12175291,57870BEBA3FF73E4,classic_bike,2023-03-31 05:46:55,2023-03-31 05:49:53,11 Ave & W 27 St,6425.04,W 34 St & 11 Ave,6578.01,40.751396,-74.005226,40.755942,-74.002116,member

In [5]:
sampled_df.to_csv("citi_bike_data/two_year_sample.csv")